[package]
name = "pg-diagrammer"
version = "0.1.0"
description = "Explorador y diagramador de bases de datos PostgreSQL"
edition = "2021"

[lib]
name = "pg_diagrammer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
base64 = "0.22"
